In [1]:
import numpy as np
x = np.ones((1,2))
def change(x):
    x += np.ones((1,2))
    return x
print(change(x))

[[2. 2.]]


In [3]:
a = np.full((2,2), 7)

In [4]:
sum(a)

array([14, 14])

In [5]:
np.sum(a)

28

In [6]:
b = np.ones((2,2,3))

In [7]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
c = np.ones((2,3))

In [9]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
d = np.ones