# Manipulation and miscellaneous

### Reshape

In [1]:
import numpy as np

np_2D = np.array([[1,2,3,4], [5, 6, 7, 8]])
print(np_2D.shape)

#-> reshape to 3D
np_3D = np_2D.reshape(2, 2, 2)
print(np_3D)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flatten

In [2]:
un_flatten = np.random.random((2, 2, 2))
print(un_flatten)

#-> flattern array
flatten = un_flatten.flatten()
print(flatten)

[[[ 0.7859413   0.98782937]
  [ 0.95983031  0.21777537]]

 [[ 0.97532131  0.89534127]
  [ 0.48024414  0.62967651]]]
[ 0.7859413   0.98782937  0.95983031  0.21777537  0.97532131  0.89534127
  0.48024414  0.62967651]


### Datatypes

- np.int64 : signed 64-bit integer types
- np.float32: standard double-precision floating point
- np.complex: complex numbers represented by 128 floats
- np.bool : Boolean type storing TRUE / FALSE
- np.object: Python object type
- np.string_ : Fixed length string type
- np.unicode_

### Inspecting

In [4]:
a = np.array([[1, 2], [3, 4]])
a.shape # array dimensions
len(a) # length of array
a.ndim # number of array dimensions
a.size # number of array elements
a.dtype # datatype of array elements


dtype('int64')

### Aggregate functions

In [6]:
a.sum() # array-wise sum
a.min() # array-wise minimum value
a.max(axis=0) # maximum value of an array row
a.mean() # mean

2.5

### Copying arrays

In [7]:
h = np.copy(a)
h = a.copy()