# Iterating array

In [2]:
import numpy as np
ar = np.arange(1, 10)
for i in np.nditer(ar): 
    print(i)

1
2
3
4
5
6
7
8
9


In [3]:
ar2 = np.random.random((2, 3))
print(ar2)
for j in np.nditer(ar2):
    print(j)

[[0.50543456 0.57661903 0.54407091]
 [0.56772404 0.60926963 0.33934384]]
0.5054345601780543
0.5766190307209696
0.5440709092173046
0.5677240377761777
0.6092696314477826
0.3393438403003334


#### Change array values while iterating

In [10]:
ar3 = np.arange(1, 5)
for i in np.nditer(ar3, op_flags=["readwrite"]):
    i[...] = i * 2
print(ar3)

[2 4 6 8]


In [13]:
float_2D = np.random.random((2, 2))
print(float_2D)
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'F'):
   print(x)

[[0.43184164 0.22774198]
 [0.76628481 0.41102846]]
[0.43184164 0.76628481]
[0.22774198 0.41102846]


In [15]:
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'C'):
   print(x)

[0.43184164 0.22774198 0.76628481 0.41102846]
